
DROP DATABASE IF EXISTS iNova; 
CREATE DATABASE iNova;
USE iNova;

CREATE TABLE dono(
id INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
numero INT, 
cod_licenca INT,
data_cadastro DATETIME 
);

CREATE TABLE empresa(
id INT NOT NULL PRIMARY KEY UNIQUE AUTO_INCREMENT,
nome_fantasia VARCHAR(70) NOT NULL,
razao_social VARCHAR(70),
contato INT, 
cnpj VARCHAR(40),
slogan VARCHAR(45)
);

CREATE TABLE pessoa (
id INT NOT NULL PRIMARY KEY UNIQUE AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
cpf VARCHAR(18) NOT NULL,
contato VARCHAR(100),
email VARCHAR(100)
);

CREATE TABLE fornecedor (
id INT NOT NULL PRIMARY KEY UNIQUE AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
cnpj VARCHAR(18) NOT NULL,
numero VARCHAR(100),
email VARCHAR(100)
);

CREATE TABLE funcionario (
id INT NOT NULL PRIMARY KEY UNIQUE AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
cpf VARCHAR(18) NOT NULL,
login VARCHAR(6) NOT NULL UNIQUE,
senha VARCHAR(6) NOT NULL,
contato VARCHAR(100),
email VARCHAR(100)
);

CREATE TABLE produto (
id INT NOT NULL PRIMARY KEY UNIQUE AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
categoria VARCHAR(18) NOT NULL,
tipo VARCHAR(20) NOT NULL,
unidade VARCHAR(20) NOT NULL,
detalhes VARCHAR(100)
);

